### PR TITLE
added zuul support

### PR DESCRIPTION
**Pull request by fredericlepied**

### CODE REVIEW

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
@sduthil do we need this packaging ?

**Comment by sduthil** [comment]
> @sduthil do we need this packaging ?

Yes, we definitely need it, it just does not change much...

**Review by rgarrigue — DISMISSED** [review]

**Comment by sduthil** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by sduthil** [comment]
Force-merging to avoid the error "package version is not greater than uploaded version". I did test the branch with an upper version, but removed it before merging to avoid useless costly downloads on Wazo Platform instances.

**Pull request merged**
